include themes/OneDark-Pro.conf

font_family JetBrains Mono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13

# Set up the tab bar
tab_bar_min_tabs            1
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         round
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Set up the background
background_opacity 0.95
background_blur 60

# Set up the window margin
window_margin_width 10

# Set default width and height
initial_window_width 100c
initial_window_height 20c 
